apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: webhook
        args:
        - python
        - -m
        - oca_github_bot
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-configmap
        ports:
        - containerPort: 8080
        resources: {}
