apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  labels:
    app: webhook
  name: webhook
spec:
  rules:
  - host: {{ .Values.webhook_hostname }}
    http:
      paths:
      - backend:
          serviceName: webhook
          servicePort: 8080
        path: /
  tls:
  - hosts:
    - {{ .Values.webhook_hostname }}
