apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: worker
        command:
        - /bin/bash
        - /scripts/entrypoint
        - celery
        - worker
        - --uid=1000
        - --concurrency=1
        - --app=oca_github_bot.queue.app
        - --loglevel=INFO
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-configmap
        volumeMounts:
        - mountPath: /app/run/.cache
          name: data
          subPath: cache
        - mountPath: /app/run/.ssh
          name: ssh-keys
          readOnly: true
        - mountPath: /scripts
          name: scripts
          readOnly: true
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: beat
        command:
        - /bin/bash
        - /scripts/entrypoint
        - celery
        - beat
        - --uid 1000
        - --app=oca_github_bot.queue.app
        - --loglevel=INFO
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-configmap
        volumeMounts:
        - mountPath: /app/run/.cache
          name: data
          subPath: cache
        - mountPath: /app/run/.ssh
          name: ssh-keys
          readOnly: true
        - mountPath: /scripts
          name: scripts
          readOnly: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-claim
      - name: ssh-keys
        secret:
          secretName: ssh-keys-secret
      - name: scripts
        configMap:
          name: scripts-configmap
